AllCops:
  NewCops: enable
  Exclude:
    - db/**/*
    - config/**/*
    - bin/**/*
    - config.ru
    - Rakefile
    - vendor/**/*
    - spec/**/*
  TargetRubyVersion: 3.1.2
  SuggestExtensions: false

# FIXME
Metrics/MethodLength:
  Max: 50

Metrics/ClassLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
